# docker-compose.prod.yml
services:
  backend:
    restart: always
    environment:
      - NODE_ENV=production
      - DEBUG=false
      - CORS_ORIGINS=https://lentera-pustaka.com
    ports: !reset [] # Pastikan port tertutup jika pakai gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    restart: always

  gateway:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  db:
    restart: always
    ports: !reset [] # Database aman dari luar
